vocab = (
    ("that we discussed", "die wie hebben gesproken over"),
    ("dog", "hond"),
    ("attention", "aandacht"),
    ("supportive; encourageing", "aanmoedigend"),
    ("liability", "aansprakelijkeid"),
    ("tip (advice)", "aanwijzing"),
    ("earth", "aarde"),
    ("behind", "achter"),
    ("occasionally", "af en toe"),
    ("last", "afgelopen"),
    ("origin (ancestry)", "afkomst"),
    ("abbrevation", "afkorting"),
    ("already", "al"),
    ("General", "algemene"),
    ("both", "allebei"),
    ("only; just", "alleen"),
    ("everything", "alles; allemaal"),
    ("always", "altijd"),
    ("job", "baan"),
    ("baby", "baby"),
    ("to start", "begginen"),
    ("except", "behalve"),
    ("both", "Beide"),
    ("important", "belangrijk"),
    ("to promise", "beloven"),
    ("mountain", "berg"),
    ("available", "beschikbaar"),
    ("to order", "bestelen"),
    ("it is still possible to try", "Bet blijft te proberen"),
    ("special", "bijzonder"),
    ("inside", "binnen"),
    ("soon", "binnenkort; straks; bijna"),
    ("to stay; to remain", "blijven"),
    ("forest", "bos"),
    ("letter", "brief"),
    ("note (written)", "brieftje"),
    ("bridge", "brug"),
    ("neighbour", "buurman"),
    ("thereafter", "daarna"),
    ("then", "Dan; Vervolgens"),
    ("to think", "denken"),
    ("The one", "Diegene"),
    ("Object; Thing", "ding"),
    ("target", "doel"),
    ("by", "door"),
    ("usually", "doorgaaans"),
    ("box", "doos"),
    ("boxes", "dozen"),
    ("to wear (clothes)", "dragen"),
    ("clear", "duidelijk"),
    ("therefore", "Dus; Daarom"),
    ("really", "echt"),
    ("however", "echter"),
    ("a few", "een paar"),
    ("first", "eerste"),
    ("actually", "eigenlijk"),
    ("end", "eind"),
    ("finally", "eindelijk"),
    ("each other", "elkaar"),
    ("some", "enkele"),
    ("somewhere", "ergens"),
    ("to be annoyed", "ergeren"),
    ("favorite", "favoriet"),
    ("to happen", "gebeuren"),
    ("to use", "gebruiken"),
    ("crazy", "gek"),
    ("ago", "geleden"),
    ("easily", "gemakkelijk"),
    ("enough", "genoeg"),
    ("to give", "geven"),
    ("curtains", "gordijnen"),
    ("to hurry", "haasten"),
    ("totally", "helemaal"),
    ("to remember", "herinneren"),
    ("it seems to me", "het lijkt me"),
    ("it is worth trying", "het valt te proberen"),
    ("same", "Hetzelfde; Zelfde"),
    ("hill", "heuvel"),
    ("quantity", "hoevelheid"),
    ("need to; have to", "hoeven"),
    ("hear", "horen"),
    ("to cry", "huilen"),
    ("something", "iets"),
    ("I'm going to get (it) myself", "ik ga zelf halen"),
    ("ticket", "kaart; kaartje"),
    ("times (occurrences)", "keer"),
    ("suitcase", "koffer"),
    ("this (Friday)", "komend (vrijdag)"),
    ("to receive", "krijgen"),
    ("pub", "kroeg"),
    ("coast", "kust"),
    ("lose; get rid of", "kwijtraken"),
    ("last", "laatste"),
    ("slow", "langzaam"),
    ("Let's", "Laten we"),
    ("empty", "leeg"),
    ("rather", "liever"),
    ("to seem", "lijken"),
    ("noisy", "luidruchtig"),
    ("moon", "maan"),
    ("basket", "mandje"),
    ("Along", "mee"),
    ("Generally; mostly", "meestal"),
    ("less", "minder"),
    ("possible", "mogelijk"),
    ("opportunity", "mogelijkeid"),
    ("currently", "momenteel"),
    ("after (that)", "nadat"),
    ("to need", "nodig hebben"),
    ("still", "nog; nog … steeds"),
    ("rather", "nogal"),
    ("never", "nooit"),
    ("in order to", "om te"),
    ("accident", "ongeluk"),
    ("approximately", "ongeveer"),
    ("independent", "onhafankelijk"),
    ("incessant", "onhopoudelijk"),
    ("immediately", "onmiddelijk"),
    ("remember", "onthouden"),
    ("to meet", "ontmoeten"),
    ("to receive", "ontvangen"),
    ("to design", "ontworpen"),
    ("ever", "ooit"),
    ("war", "oorlog"),
    ("public transport", "openbaar voorvoer"),
    ("solution", "oplossing"),
    ("again", "opnieuw; weer"),
    ("perfect", "perfect"),
    ("pencil", "potlood"),
    ("to try", "proberen"),
    ("window", "raam"),
    ("reasonable", "redelijk"),
    ("regular", "regelmatig"),
    ("to travel", "reizen"),
    ("to run away", "rennen weg"),
    ("to ride", "rijden"),
    ("wealthy", "rijk"),
    ("to clean (up)", "ruimen"),
    ("Quiet; Calm", "rustige"),
    ("to pass (an exam)", "slagen voor (geslaagd zijn voor)"),
    ("sometimes", "soms"),
    ("to play", "spelen"),
    ("star", "ster"),
    ("galaxy", "sterrenstelsel"),
    ("to aim", "streven"),
    ("too (excessively)", "te"),
    ("against", "tegen"),
    ("opposite", "tegengestelde"),
    ("phone call", "telefoontje"),
    ("to count", "tellen"),
    ("however", "toch"),
    ("future (noun)", "toekomst"),
    ("future (adjective)", "toekomstige"),
    ("to show", "tonen"),
    ("until (included)", "tot en met"),
    ("besides", "trouwens"),
    ("except", "uitgezonderd"),
    ("watch out", "uitkijken"),
    ("excellent", "uitsteken"),
    ("urgent", "urgent"),
    ("often", "vaak"),
    ("is it worth a try?", "valt het te proberen?"),
    ("far", "ver"),
    ("to change; to modify", "veranderen"),
    ("to be amazed", "verbazen"),
    ("to earn", "verdienen"),
    ("story", "verhaal"),
    ("to afford", "veroorloven"),
    ("different", "verschillende"),
    ("to leave", "Vertrekken"),
    ("to be bored", "vervelen"),
    ("annoying", "vervelend"),
    ("to request", "verzoeken"),
    ("airport", "vliegveld"),
    ("football", "voetballen"),
    ("enough", "voldoende"),
    ("to follow", "volgen"),
    ("mainly", "voornamelijk; vooral"),
    ("to imagine", "voorstellen"),
    ("previous", "vorig"),
    ("to ask", "vragen"),
    ("fire", "vuur"),
    ("to wait", "wachten"),
    ("we look forward to it", "we verheugen ons erop"),
    ("little; few", "weinig"),
    ("ever", "weleens"),
    ("world", "wereld"),
    ("match; contest", "westrijd"),
    ("to know", "weten"),
    ("wheel", "wiel"),
    ("(a) change", "wijziging"),
    ("vocabulary", "woordenschat"),
    ("to become", "worden"),
    ("is becoming", "wordt"),
    ("very", "zeer"),
    ("seldom; rarely", "zelden"),
    ("even", "zelfs"),
    ("to put", "zetten"),
    ("to sing", "zingen"),
    ("such a thing", "zoeits"),
    ("to look (for)", "zoeken"),
    ("Just (the train just left)", "zojuist"),
    ("without", "zonder"),
    ("such (such animal)", "zulk"),
    ("heavy", "zwaar"),
    ("to be surprised", "verrast zijn"),
)

import random
english,dutch=random.choice(vocab)
print(english)
answer=input("What is the Dutch word for...?")
if answer==dutch:
    print("ja!")
else:
    print("nee!", dutch)
